Page_Controller:
  extensions:
    - YearCalendarControllerInit

YearCalendarItem:
  extensions:
    - TranslatableDataObject

YearCalendarItemTag:
  extensions:
    - TranslatableDataObject

YearCalendarAdmin:
  itemsPerPage: 150